unique_ids:
  forms:
    Form1: OWKRAQYBKZ6P7PGUFM72E3N37HMYVVFE
    Form1.ItemTemplate1: '1719193782653202317590915.72067'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: BGIMT3OO2E5FWN7IGAQ5WVXVNLQ2V5QI
    theme.css: LOF7QN6RFUPBDQECKWK4AVPX6M667FH5
  scripts: {}
